name: Python Linting and CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint with flake8
        run: |
          # Ignore line length (E501), you can tune this later
          flake8 . --exclude=venv.__pycache__ --ignore=E501
      
      - name: Run tests with coverge
        run: |
          pytest --cov=secondmind --cov-report=xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token:
          files: coverage.xml
          fail_ci_if_error: true


